config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/welcome/create', to: 'welcome#create_user', as: 'create_user'
  post '/welcome/create', to: 'welcome#post_user', as: 'post_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  @api = 'http://json-server.devpointlabs.com/api/v1/users'

  def index
    @user = HTTParty.get('http://json-server.devpointlabs.com/api/v1/users')
  end

  def create_user
    @user = 'users'
  end

  def post_user
    first = params[:users][:first_name]
    last = params[:users][:last_name]
    number = params[:users][:phone_number]
    HTTParty.post('http://json-server.devpointlabs.com/api/v1/users', body: {'user[first_name]': first, 'user[last_name]': last, 'user[phone_number]': number})
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsersHttparty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/create_user.html.erb
<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

 <%= f.label :last_name %>
  <%= f.text_field :last_name %>

 <%= f.label :phone_number %>
  <%= f.text_area :phone_number %>

 <%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>People</h1>
<%= link_to 'Add new user', create_user_path %>
<ul>
  <% @user.each do |person| %>
    <li><%= person['first_name'] %></li>
    <li><%= person["last_name"] %></li>
    <li><%= person['phone_number'] %></li>
    <hr>
  <% end %>

</ul>